package com.caps.eteeapp.model;

public enum DocumentType {
    APPLICANTS_EVALUATION_SHEET,
    INFORMATIVE_COPY_OF_TOR,
    PSA_AUTHENTICATED_BIRTH_CERTIFICATE,
    CERTIFICATE_OF_TRANSFER_CREDENTIAL,
    MARRIAGE_CERTIFICATE,
    CERTIFICATE_OF_EMPLOYMENT,
    EMPLOYER_CERTIFIED_DETAILED_JOB_DESCRIPTION,
    EVIDENCE_OF_BUSINESS_OWNERSHIP,
    VALID_ID,
    DIPLOMA,
    TRANSCRIPT_OF_RECORDS,
    CERTIFICATION_OF_GRADES,
    RECOMMENDATION_LETTER,
    CURRICULUM_VITAE,
    MEDICAL_CERTIFICATE,
    APPLICATION_FORM,
    OTHER_DOCUMENT
}
